# permissions for end users to edit appdeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdeployer-editor-role
rules:
- apiGroups:
  - deployer.radisys.com
  resources:
  - appdeployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployer.radisys.com
  resources:
  - appdeployers/status
  verbs:
  - get
